project:
  type: website
  output-dir: docs

website:
  title: "Ellie M-U Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Test.qmd
        text: Test

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

